# Generated by Django 2.2.3 on 2019-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='task_number_in_course',
            field=models.IntegerField(default=0),
        ),
    ]
